import pytest
import decimal
import datetime
from sqlalchemy import text, select, Column, Integer, BigInteger, Float, Boolean, String, Numeric, Date, Time, DateTime
from sqlalchemy.orm import declarative_base

Base = declarative_base()

@pytest.mark.asyncio
async def test_complex_types_fb4(async_engine):
    """
    Тестирование сложных типов Firebird 4 (INT128, Time Zones, Blobs).
    """
    now_tz = datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0)
    test_val_38 = decimal.Decimal("1234567890123456789012345678.9012345678")
    test_blob = "Very large text blob " * 100

    # 1. DDL (отдельная транзакция)
    async with async_engine.begin() as conn:
        try: await conn.execute(text("DROP TABLE complex_types"))
        except Exception: pass
        
        await conn.execute(text("""
            CREATE TABLE complex_types (
                id INTEGER PRIMARY KEY,
                f_numeric_38 NUMERIC(38, 10),
                f_timestamp_tz TIMESTAMP WITH TIME ZONE,
                f_blob BLOB SUB_TYPE TEXT
            )
        """))

    # 2. INSERT (отдельная транзакция)
    async with async_engine.begin() as conn:
        await conn.execute(
            text("""
                INSERT INTO complex_types (id, f_numeric_38, f_timestamp_tz, f_blob)
                VALUES (:id, :f_numeric_38, :f_timestamp_tz, :f_blob)
            """),
            {
                "id": 1,
                "f_numeric_38": test_val_38,
                "f_timestamp_tz": now_tz,
                "f_blob": test_blob
            }
        )

    # 3. SELECT
    async with async_engine.connect() as conn:
        result = await conn.execute(text("SELECT * FROM complex_types WHERE id = 1"))
        row = result.fetchone()
        assert row.f_numeric_38 == test_val_38
        assert isinstance(row.f_timestamp_tz, datetime.datetime)
        assert abs(row.f_timestamp_tz.timestamp() - now_tz.timestamp()) < 1.0
        assert row.f_blob == test_blob

@pytest.mark.asyncio
async def test_numeric_precision_where(async_engine):
    val = decimal.Decimal("99999999.99")
    async with async_engine.begin() as conn:
        try: await conn.execute(text("DROP TABLE test_num"))
        except Exception: pass
        await conn.execute(text("CREATE TABLE test_num (v NUMERIC(10,2))"))
    
    async with async_engine.begin() as conn:
        await conn.execute(text("INSERT INTO test_num (v) VALUES (:v)"), {"v": val})
        
    async with async_engine.connect() as conn:
        res = await conn.execute(text("SELECT v FROM test_num WHERE v = :v"), {"v": val})
        assert res.scalar() == val

@pytest.mark.asyncio
async def test_aggregations(async_engine):
    async with async_engine.begin() as conn:
        try: await conn.execute(text("DROP TABLE test_agg"))
        except Exception: pass
        await conn.execute(text("CREATE TABLE test_agg (val DECIMAL(10,2))"))
    
    async with async_engine.begin() as conn:
        for v in [10.5, 20.5, 30.0]:
            await conn.execute(text("INSERT INTO test_agg (val) VALUES (:v)"), {"v": v})
        
    async with async_engine.connect() as conn:
        res = await conn.execute(text("SELECT SUM(val), COUNT(*) FROM test_agg"))
        s, c = res.fetchone()
        assert s == decimal.Decimal("61.00")
        assert c == 3

@pytest.mark.asyncio
async def test_insert_returning(async_engine):
    async with async_engine.begin() as conn:
        try: await conn.execute(text("DROP TABLE test_ret"))
        except Exception: pass
        await conn.execute(text("CREATE TABLE test_ret (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(50))"))
    
    async with async_engine.begin() as conn:
        res = await conn.execute(
            text("INSERT INTO test_ret (name) VALUES (:name) RETURNING id"),
            {"name": "test"}
        )
        new_id = res.scalar()
        assert isinstance(new_id, int)

@pytest.mark.asyncio
async def test_statement_string_compilation(async_engine):
    stmt = text("SELECT 1 FROM rdb$database WHERE 1 = :id").bindparams(id=1)
    compiled_str = str(stmt.compile(async_engine.sync_engine))
    assert "1 = " in compiled_str